export const LOGIN_SUCCEED = 'LOGIN/SUCCEED';

export const LOGIN_FAILED = 'LOGIN/FAILED';

export const LOGIN_STATE_VALID = 'LOGIN/LOGIN_STATE_VALID';

export const LOGIN_STATE_INVALID = 'LOGIN/LOGIN_STATE_INVALID';
