export default {
    LOGOUT_MODAL: 'logoutModal',
    ADD_SCREEN_MODAL: 'addScreenModal',
    CHANGE_SCREEN_MODAL: 'changeScreenModal',
    DELETE_SCREEN_MODAL: 'deleteScreenModal',
    BIND_RESOURCE_PACK_MODAL: 'bindResourcePackModal',
    UNBIND_RESOURCE_PACK_MODAL: 'unbindResourcePackModal',
    UPLOAD_VIDEO_INFO_MODAL: 'uploadVideoModal',
    UPLOAD_IMAGE_INFO_MODAL: 'uploadImageModal',
    ADVERTISEMENT_INFO_MODAL: 'advertisementInfoModal',
    DELETE_ADVERTISEMENT_MODAL: 'deleteAdvertisementModal',
    TAG_INFO_MODAL: 'tagInfoModal',
    DELETE_TAG_MODAL: 'deleteTagModal',
    RESOURCE_PACK_MANAGEMENT_SELECT_ADVERTISEMENT_MODAL: 'resourcePackManagementSelectAdvertisementModal',
    RESOURCE_PACK_TAG_NAME_LIST_MODAL: 'resourcePackTagNameListModal',
    RESOURCE_PACK_ADVERTISEMENT_LIST_MODAL: 'resourcePackAdvertisementListModal',
    RESOURCE_PACK_SCREEN_LIST_MODAL: 'resourcePackScreenNameListModal',
    RESOURCE_PACK_CHANGE_MODAL: 'resourcePackChangeModal',
    DELETE_RESOURCE_PACK_MODAL: 'deleteResourcePackModal',
};