export default {
    LOGOUT_MODAL: 'logoutModal',
    ADD_SCREEN_MODAL: 'addScreenModal',
    BIND_RESOURCE_PACK_MODAL: 'bindResourcePackModal',
    UNBIND_RESOURCE_PACK_MODAL: 'unbindResourcePackModal',
    DELETE_SCREEN_MODAL: 'deleteScreenModal',
    START_SCREEN_RUNNING_MODAL: 'startScreenRunningModal',
    STOP_SCREEN_RUNNING_MODAL: 'stopScreenRunningModal',
    BATCH_BIND_RESOURCE_PACK_MODAL: 'batchBindResourcePackModal',
    BATCH_UNBIND_RESOURCE_PACK_MODAL: 'batchUnbindResourcePackModal',
    UPLOAD_VIDEO_INFO_MODAL: 'uploadVideoModal',
    UPLOAD_IMAGE_INFO_MODAL: 'uploadImageModal',
    ADVERTISEMENT_INFO_MODAL: 'advertisementInfoModal',
    TAG_INFO_MODAL: 'tagInfoModal',
    RESOURCE_PACK_MANAGEMENT_SELECT_ADVERTISEMENT_MODAL: 'resourcePackManagementSelectAdvertisementModal',
    RESOURCE_PACK_TAG_NAME_LIST_MODAL: 'resourcePackTagNameListModal',
    RESOURCE_PACK_ADVERTISEMENT_LIST_MODAL: 'resourcePackAdvertisementListModal',
    RESOURCE_PACK_SCREEN_LIST_MODAL: 'resourcePackScreenNameListModal',
    RESOURCE_PACK_CHANGE_MODAL: 'resourcePackChangeModal',
};