export const SELECT_SCREEN = 'SCREEN_MANAGEMENT/SCREEN_LIST_CARD/SELECT_SCREEN';

export const UNSELECT_SCREEN = 'SCREEN_MANAGEMENT/SCREEN_LIST_CARD/UNSELECT_SCREEN';

export const SELECT_ALL_SCREENS = 'SCREEN_MANAGEMENT/SCREEN_LIST_CARD/SELECT_ALL_SCREENS';

export const UNSELECT_ALL_SCREENS = 'SCREEN_MANAGEMENT/SCREEN_LIST_CARD/UNSELECT_ALL_SCREENS';